[window]
width = 600
height = 600
anchor = "center"
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
show_descriptions = false
show_paths = false
show_icons = true
show_search = true
show_actions = false
show_border = true
border_width = 2
use_gtk_colors = false
use_custom_css = false
max_entries = 50

[window.custom_navigate_keys]
up = "k"
down = "j"
delete_word = "h"

[theme.colors]
window_bg = "#282828"
search_bg = "#1d2021"
search_bg_focused = "#a89984"
item_bg = "#504945"
item_bg_hover = "#665c54"
item_bg_selected = "#32402f"
search_text = "#fbf1c7"
search_caret = "#928374"
item_name = "#edbbb2"
item_name_selected = "#ffffff"
item_description = "#a0a0a0"
item_description_selected = "#a0a0a0"
item_path = "#3c3836"
item_path_selected = "#808080"
border = "#689d6a"

[theme.corners]
window = 6
search = 8
list_item = 6 

[theme.spacing]
search_margin = 12
search_padding = 12
item_margin = 2
item_padding = 4

[theme.typography]
search_font_size = 20 
item_name_size = 18
item_description_size = 12
item_path_size = 6 
item_path_font_family = "monospace"

[debug]
disable_auto_focus = false
enable_logging = false

[dmenu]
allow_invalid = false
case_sensitive = false

[web_search]
enabled = false
engine = "duckduckgo"
prefixes = []
